#!/bin/bash
set -e
PROJECT=t_hospitality
LOCALE=${1:-en_EN.UTF-8}
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DROP DATABASE IF EXISTS $PROJECT;
DROP USER IF EXISTS $PROJECT;
CREATE USER $PROJECT WITH PASSWORD '$PROJECT';
CREATE DATABASE $PROJECT
    OWNER $PROJECT
    ENCODING 'UTF-8'
    LC_COLLATE '$LOCALE'
    LC_CTYPE '$LOCALE'
    TEMPLATE template0;
\connect $PROJECT;
CREATE SCHEMA AUTHORIZATION $PROJECT;
CREATE EXTENSION btree_gist;
CREATE EXTENSION pg_trgm WITH SCHEMA pg_catalog;
EOSQL
