services:
  PostgreSQL:
    build: ./PostgreSQL
    container_name: PostgreSQL
    ports:
      - "5432:5432"
    environment:
      LANG: en_US.utf8
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_INITDB_ARGS_FILE: /run/secrets/postgres_initdb_args
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
      - postgres_initdb_args
secrets:
  postgres_db:
    file: PostgreSQL/.secrets/postgres_db
  postgres_user:
    file: PostgreSQL/.secrets/postgres_user
  postgres_password:
    file: PostgreSQL/.secrets/postgres_password
  postgres_initdb_args:
    file: PostgreSQL/.secrets/postgres_initdb_args
  